services:
  database:
    image: "postgres:16.1-alpine3.19"
    environment:
      POSTGRES_PASSWORD: "local_password"
      POSTGRES_USER: "rga_user"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
