-- CreateEnum
CREATE TYPE "FORNECEDORES" AS ENUM ('FORNECEDOR_PRINCIPAL', 'FORNECEDOR_SECUNDARIO');

-- AlterTable
ALTER TABLE "toppers" ADD COLUMN     "fornecedor" "FORNECEDORES" NOT NULL DEFAULT 'FORNECEDOR_PRINCIPAL';
